---
- name: Windows VM creation
  hosts: localhost
  vars:
    vcenter_provider:
      hostname: lab-vcsa.lab.local
      username: parise
      password: Password02
      validate_certs: False
      datacenter: LAB-Datacenter
      cluster: LAB-Cluster
      folder: Orchestration

    source_vm:
      name: 'Lab-template2016-vmversion13'
      network_name: 'VM Network'

    

    new_hosts:
      - hostname: lab-ans-win01
      - hostname: lab-ans-win02
      - hostname: lab-ans-win03

  tasks:
    - name: Creating VM from template
      vmware_guest:
        hostname: "{{ vcenter_provider.hostname }}"
        username: "{{ vcenter_provider.username }}"
        password: "{{ vcenter_provider.password }}"
        datacenter: "{{ vcenter_provider.datacenter }}"
        cluster: "{{ vcenter_provider.cluster }}"
        validate_certs: "{{ vcenter_provider.validate_certs }}"
        folder: "{{( vcenter_provider.folder | default ('/vm') )}}"
        name: "{{ item.hostname }}"
        state: "{{ item.state | default('poweredon') }}"
        template: "{{ source_vm.name }}"
        networks:
          - name: "{{ source_vm.network_name }}"
        customization:
          hostname: "{{ item.hostname }}"
          
        annotation: "Eurosystem VM customization"
        with_items: "{{ new_hosts }}"
      register: deploy

    - name: Show Deploy
      debug:
        msg: "{{ deploy }}"


      