---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ lab-vcsa.lab.local }}"
      username: "{{ administrator }}"
      password: "{{ Password01 }}"
      validate_certs: False
      name: testansible01
      template: Lab-template2016-vmversion13
      datacenter: "{{ LAB-Datacenter }}"
      folder: Orchestration
      state: poweredon
      cluster: "{{ LAB-Cluster }}"
      wait_for_ip_address: yes